export interface TimezoneOption {
  id: string;
  country: string;
  city: string;
  zone: string;
}

export const TIMEZONE_OPTIONS: TimezoneOption[] = [
  { id: "asia-kabul", country: "Afghanistan", city: "Kabul", zone: "Asia/Kabul" },
  { id: "europe-mariehamn", country: "Åland Islands", city: "Mariehamn", zone: "Europe/Mariehamn" },
  { id: "europe-tirane", country: "Albania", city: "Tirane", zone: "Europe/Tirane" },
  { id: "africa-algiers", country: "Algeria", city: "Algiers", zone: "Africa/Algiers" },
  { id: "pacific-pago-pago", country: "American Samoa", city: "Pago Pago", zone: "Pacific/Pago_Pago" },
  { id: "europe-andorra", country: "Andorra", city: "Andorra", zone: "Europe/Andorra" },
  { id: "africa-luanda", country: "Angola", city: "Luanda", zone: "Africa/Luanda" },
  { id: "america-anguilla", country: "Anguilla", city: "Anguilla", zone: "America/Anguilla" },
  { id: "antarctica-casey", country: "Antarctica", city: "Casey", zone: "Antarctica/Casey" },
  { id: "antarctica-davis", country: "Antarctica", city: "Davis", zone: "Antarctica/Davis" },
  { id: "antarctica-dumontdurville", country: "Antarctica", city: "DumontDUrville", zone: "Antarctica/DumontDUrville" },
  { id: "antarctica-mawson", country: "Antarctica", city: "Mawson", zone: "Antarctica/Mawson" },
  { id: "antarctica-mcmurdo", country: "Antarctica", city: "McMurdo", zone: "Antarctica/McMurdo" },
  { id: "antarctica-palmer", country: "Antarctica", city: "Palmer", zone: "Antarctica/Palmer" },
  { id: "antarctica-rothera", country: "Antarctica", city: "Rothera", zone: "Antarctica/Rothera" },
  { id: "antarctica-syowa", country: "Antarctica", city: "Syowa", zone: "Antarctica/Syowa" },
  { id: "antarctica-troll", country: "Antarctica", city: "Troll", zone: "Antarctica/Troll" },
  { id: "antarctica-vostok", country: "Antarctica", city: "Vostok", zone: "Antarctica/Vostok" },
  { id: "america-antigua", country: "Antigua and Barbuda", city: "Antigua", zone: "America/Antigua" },
  { id: "america-argentina-la-rioja", country: "Argentina", city: "Argentina – La Rioja", zone: "America/Argentina/La_Rioja" },
  { id: "america-argentina-rio-gallegos", country: "Argentina", city: "Argentina – Rio Gallegos", zone: "America/Argentina/Rio_Gallegos" },
  { id: "america-argentina-salta", country: "Argentina", city: "Argentina – Salta", zone: "America/Argentina/Salta" },
  { id: "america-argentina-san-juan", country: "Argentina", city: "Argentina – San Juan", zone: "America/Argentina/San_Juan" },
  { id: "america-argentina-san-luis", country: "Argentina", city: "Argentina – San Luis", zone: "America/Argentina/San_Luis" },
  { id: "america-argentina-tucuman", country: "Argentina", city: "Argentina – Tucuman", zone: "America/Argentina/Tucuman" },
  { id: "america-argentina-ushuaia", country: "Argentina", city: "Argentina – Ushuaia", zone: "America/Argentina/Ushuaia" },
  { id: "america-buenos-aires", country: "Argentina", city: "Buenos Aires", zone: "America/Buenos_Aires" },
  { id: "america-catamarca", country: "Argentina", city: "Catamarca", zone: "America/Catamarca" },
  { id: "america-cordoba", country: "Argentina", city: "Cordoba", zone: "America/Cordoba" },
  { id: "america-jujuy", country: "Argentina", city: "Jujuy", zone: "America/Jujuy" },
  { id: "america-mendoza", country: "Argentina", city: "Mendoza", zone: "America/Mendoza" },
  { id: "asia-yerevan", country: "Armenia", city: "Yerevan", zone: "Asia/Yerevan" },
  { id: "america-aruba", country: "Aruba", city: "Aruba", zone: "America/Aruba" },
  { id: "australia-adelaide", country: "Australia", city: "Adelaide", zone: "Australia/Adelaide" },
  { id: "australia-brisbane", country: "Australia", city: "Brisbane", zone: "Australia/Brisbane" },
  { id: "australia-broken-hill", country: "Australia", city: "Broken Hill", zone: "Australia/Broken_Hill" },
  { id: "indian-christmas", country: "Australia", city: "Christmas", zone: "Indian/Christmas" },
  { id: "indian-cocos", country: "Australia", city: "Cocos", zone: "Indian/Cocos" },
  { id: "australia-darwin", country: "Australia", city: "Darwin", zone: "Australia/Darwin" },
  { id: "australia-eucla", country: "Australia", city: "Eucla", zone: "Australia/Eucla" },
  { id: "australia-hobart", country: "Australia", city: "Hobart", zone: "Australia/Hobart" },
  { id: "australia-lindeman", country: "Australia", city: "Lindeman", zone: "Australia/Lindeman" },
  { id: "australia-lord-howe", country: "Australia", city: "Lord Howe", zone: "Australia/Lord_Howe" },
  { id: "antarctica-macquarie", country: "Australia", city: "Macquarie", zone: "Antarctica/Macquarie" },
  { id: "australia-melbourne", country: "Australia", city: "Melbourne", zone: "Australia/Melbourne" },
  { id: "pacific-norfolk", country: "Australia", city: "Norfolk", zone: "Pacific/Norfolk" },
  { id: "australia-perth", country: "Australia", city: "Perth", zone: "Australia/Perth" },
  { id: "australia-sydney", country: "Australia", city: "Sydney", zone: "Australia/Sydney" },
  { id: "europe-vienna", country: "Austria", city: "Vienna", zone: "Europe/Vienna" },
  { id: "asia-baku", country: "Azerbaijan", city: "Baku", zone: "Asia/Baku" },
  { id: "america-nassau", country: "Bahamas", city: "Nassau", zone: "America/Nassau" },
  { id: "asia-bahrain", country: "Bahrain", city: "Bahrain", zone: "Asia/Bahrain" },
  { id: "asia-dhaka", country: "Bangladesh", city: "Dhaka", zone: "Asia/Dhaka" },
  { id: "america-barbados", country: "Barbados", city: "Barbados", zone: "America/Barbados" },
  { id: "europe-minsk", country: "Belarus", city: "Minsk", zone: "Europe/Minsk" },
  { id: "europe-brussels", country: "Belgium", city: "Brussels", zone: "Europe/Brussels" },
  { id: "america-belize", country: "Belize", city: "Belize", zone: "America/Belize" },
  { id: "africa-porto-novo", country: "Benin", city: "Porto-Novo", zone: "Africa/Porto-Novo" },
  { id: "atlantic-bermuda", country: "Bermuda", city: "Bermuda", zone: "Atlantic/Bermuda" },
  { id: "asia-thimphu", country: "Bhutan", city: "Thimphu", zone: "Asia/Thimphu" },
  { id: "america-la-paz", country: "Bolivia", city: "La Paz", zone: "America/La_Paz" },
  { id: "europe-sarajevo", country: "Bosnia and Herzegovina", city: "Sarajevo", zone: "Europe/Sarajevo" },
  { id: "africa-gaborone", country: "Botswana", city: "Gaborone", zone: "Africa/Gaborone" },
  { id: "america-araguaina", country: "Brazil", city: "Araguaina", zone: "America/Araguaina" },
  { id: "america-bahia", country: "Brazil", city: "Bahia", zone: "America/Bahia" },
  { id: "america-belem", country: "Brazil", city: "Belem", zone: "America/Belem" },
  { id: "america-boa-vista", country: "Brazil", city: "Boa Vista", zone: "America/Boa_Vista" },
  { id: "america-campo-grande", country: "Brazil", city: "Campo Grande", zone: "America/Campo_Grande" },
  { id: "america-cuiaba", country: "Brazil", city: "Cuiaba", zone: "America/Cuiaba" },
  { id: "america-eirunepe", country: "Brazil", city: "Eirunepe", zone: "America/Eirunepe" },
  { id: "america-fortaleza", country: "Brazil", city: "Fortaleza", zone: "America/Fortaleza" },
  { id: "america-maceio", country: "Brazil", city: "Maceio", zone: "America/Maceio" },
  { id: "america-manaus", country: "Brazil", city: "Manaus", zone: "America/Manaus" },
  { id: "america-noronha", country: "Brazil", city: "Noronha", zone: "America/Noronha" },
  { id: "america-porto-velho", country: "Brazil", city: "Porto Velho", zone: "America/Porto_Velho" },
  { id: "america-recife", country: "Brazil", city: "Recife", zone: "America/Recife" },
  { id: "america-rio-branco", country: "Brazil", city: "Rio Branco", zone: "America/Rio_Branco" },
  { id: "america-santarem", country: "Brazil", city: "Santarem", zone: "America/Santarem" },
  { id: "america-sao-paulo", country: "Brazil", city: "Sao Paulo", zone: "America/Sao_Paulo" },
  { id: "indian-chagos", country: "British Indian Ocean Territory", city: "Chagos", zone: "Indian/Chagos" },
  { id: "america-tortola", country: "British Virgin Islands", city: "Tortola", zone: "America/Tortola" },
  { id: "asia-brunei", country: "Brunei", city: "Brunei", zone: "Asia/Brunei" },
  { id: "europe-sofia", country: "Bulgaria", city: "Sofia", zone: "Europe/Sofia" },
  { id: "africa-ouagadougou", country: "Burkina Faso", city: "Ouagadougou", zone: "Africa/Ouagadougou" },
  { id: "africa-bujumbura", country: "Burundi", city: "Bujumbura", zone: "Africa/Bujumbura" },
  { id: "atlantic-cape-verde", country: "Cabo Verde", city: "Cape Verde", zone: "Atlantic/Cape_Verde" },
  { id: "asia-phnom-penh", country: "Cambodia", city: "Phnom Penh", zone: "Asia/Phnom_Penh" },
  { id: "africa-douala", country: "Cameroon", city: "Douala", zone: "Africa/Douala" },
  { id: "america-blanc-sablon", country: "Canada", city: "Blanc-Sablon", zone: "America/Blanc-Sablon" },
  { id: "america-cambridge-bay", country: "Canada", city: "Cambridge Bay", zone: "America/Cambridge_Bay" },
  { id: "america-coral-harbour", country: "Canada", city: "Coral Harbour", zone: "America/Coral_Harbour" },
  { id: "america-creston", country: "Canada", city: "Creston", zone: "America/Creston" },
  { id: "america-dawson", country: "Canada", city: "Dawson", zone: "America/Dawson" },
  { id: "america-dawson-creek", country: "Canada", city: "Dawson Creek", zone: "America/Dawson_Creek" },
  { id: "america-edmonton", country: "Canada", city: "Edmonton", zone: "America/Edmonton" },
  { id: "america-fort-nelson", country: "Canada", city: "Fort Nelson", zone: "America/Fort_Nelson" },
  { id: "america-glace-bay", country: "Canada", city: "Glace Bay", zone: "America/Glace_Bay" },
  { id: "america-goose-bay", country: "Canada", city: "Goose Bay", zone: "America/Goose_Bay" },
  { id: "america-halifax", country: "Canada", city: "Halifax", zone: "America/Halifax" },
  { id: "america-inuvik", country: "Canada", city: "Inuvik", zone: "America/Inuvik" },
  { id: "america-iqaluit", country: "Canada", city: "Iqaluit", zone: "America/Iqaluit" },
  { id: "america-moncton", country: "Canada", city: "Moncton", zone: "America/Moncton" },
  { id: "america-rankin-inlet", country: "Canada", city: "Rankin Inlet", zone: "America/Rankin_Inlet" },
  { id: "america-regina", country: "Canada", city: "Regina", zone: "America/Regina" },
  { id: "america-resolute", country: "Canada", city: "Resolute", zone: "America/Resolute" },
  { id: "america-st-johns", country: "Canada", city: "St Johns", zone: "America/St_Johns" },
  { id: "america-swift-current", country: "Canada", city: "Swift Current", zone: "America/Swift_Current" },
  { id: "america-toronto", country: "Canada", city: "Toronto", zone: "America/Toronto" },
  { id: "america-vancouver", country: "Canada", city: "Vancouver", zone: "America/Vancouver" },
  { id: "america-whitehorse", country: "Canada", city: "Whitehorse", zone: "America/Whitehorse" },
  { id: "america-winnipeg", country: "Canada", city: "Winnipeg", zone: "America/Winnipeg" },
  { id: "america-kralendijk", country: "Caribbean Netherlands", city: "Kralendijk", zone: "America/Kralendijk" },
  { id: "america-cayman", country: "Cayman Islands", city: "Cayman", zone: "America/Cayman" },
  { id: "africa-bangui", country: "Central African Republic", city: "Bangui", zone: "Africa/Bangui" },
  { id: "africa-ndjamena", country: "Chad", city: "Ndjamena", zone: "Africa/Ndjamena" },
  { id: "america-coyhaique", country: "Chile", city: "Coyhaique", zone: "America/Coyhaique" },
  { id: "pacific-easter", country: "Chile", city: "Easter", zone: "Pacific/Easter" },
  { id: "america-punta-arenas", country: "Chile", city: "Punta Arenas", zone: "America/Punta_Arenas" },
  { id: "america-santiago", country: "Chile", city: "Santiago", zone: "America/Santiago" },
  { id: "asia-shanghai", country: "China", city: "Shanghai", zone: "Asia/Shanghai" },
  { id: "asia-urumqi", country: "China", city: "Urumqi", zone: "Asia/Urumqi" },
  { id: "america-bogota", country: "Colombia", city: "Bogota", zone: "America/Bogota" },
  { id: "indian-comoro", country: "Comoros", city: "Comoro", zone: "Indian/Comoro" },
  { id: "africa-brazzaville", country: "Congo", city: "Brazzaville", zone: "Africa/Brazzaville" },
  { id: "pacific-rarotonga", country: "Cook Islands", city: "Rarotonga", zone: "Pacific/Rarotonga" },
  { id: "america-costa-rica", country: "Costa Rica", city: "Costa Rica", zone: "America/Costa_Rica" },
  { id: "africa-abidjan", country: "Côte d'Ivoire", city: "Abidjan", zone: "Africa/Abidjan" },
  { id: "europe-zagreb", country: "Croatia", city: "Zagreb", zone: "Europe/Zagreb" },
  { id: "america-havana", country: "Cuba", city: "Havana", zone: "America/Havana" },
  { id: "america-curacao", country: "Curaçao", city: "Curacao", zone: "America/Curacao" },
  { id: "asia-famagusta", country: "Cyprus", city: "Famagusta", zone: "Asia/Famagusta" },
  { id: "asia-nicosia", country: "Cyprus", city: "Nicosia", zone: "Asia/Nicosia" },
  { id: "europe-prague", country: "Czechia", city: "Prague", zone: "Europe/Prague" },
  { id: "europe-copenhagen", country: "Denmark", city: "Copenhagen", zone: "Europe/Copenhagen" },
  { id: "africa-djibouti", country: "Djibouti", city: "Djibouti", zone: "Africa/Djibouti" },
  { id: "america-dominica", country: "Dominica", city: "Dominica", zone: "America/Dominica" },
  { id: "america-santo-domingo", country: "Dominican Republic", city: "Santo Domingo", zone: "America/Santo_Domingo" },
  { id: "africa-kinshasa", country: "DR Congo", city: "Kinshasa", zone: "Africa/Kinshasa" },
  { id: "africa-lubumbashi", country: "DR Congo", city: "Lubumbashi", zone: "Africa/Lubumbashi" },
  { id: "asia-dili", country: "East Timor", city: "Dili", zone: "Asia/Dili" },
  { id: "pacific-galapagos", country: "Ecuador", city: "Galapagos", zone: "Pacific/Galapagos" },
  { id: "america-guayaquil", country: "Ecuador", city: "Guayaquil", zone: "America/Guayaquil" },
  { id: "africa-cairo", country: "Egypt", city: "Cairo", zone: "Africa/Cairo" },
  { id: "america-el-salvador", country: "El Salvador", city: "El Salvador", zone: "America/El_Salvador" },
  { id: "africa-malabo", country: "Equatorial Guinea", city: "Malabo", zone: "Africa/Malabo" },
  { id: "africa-asmera", country: "Eritrea", city: "Asmera", zone: "Africa/Asmera" },
  { id: "europe-tallinn", country: "Estonia", city: "Tallinn", zone: "Europe/Tallinn" },
  { id: "africa-mbabane", country: "Eswatini", city: "Mbabane", zone: "Africa/Mbabane" },
  { id: "africa-addis-ababa", country: "Ethiopia", city: "Addis Ababa", zone: "Africa/Addis_Ababa" },
  { id: "atlantic-stanley", country: "Falkland Islands", city: "Stanley", zone: "Atlantic/Stanley" },
  { id: "atlantic-faeroe", country: "Faroe Islands", city: "Faeroe", zone: "Atlantic/Faeroe" },
  { id: "pacific-fiji", country: "Fiji", city: "Fiji", zone: "Pacific/Fiji" },
  { id: "europe-helsinki", country: "Finland", city: "Helsinki", zone: "Europe/Helsinki" },
  { id: "europe-paris", country: "France", city: "Paris", zone: "Europe/Paris" },
  { id: "america-cayenne", country: "French Guiana", city: "Cayenne", zone: "America/Cayenne" },
  { id: "pacific-gambier", country: "French Polynesia", city: "Gambier", zone: "Pacific/Gambier" },
  { id: "pacific-marquesas", country: "French Polynesia", city: "Marquesas", zone: "Pacific/Marquesas" },
  { id: "pacific-tahiti", country: "French Polynesia", city: "Tahiti", zone: "Pacific/Tahiti" },
  { id: "indian-kerguelen", country: "French Southern Territories", city: "Kerguelen", zone: "Indian/Kerguelen" },
  { id: "africa-libreville", country: "Gabon", city: "Libreville", zone: "Africa/Libreville" },
  { id: "africa-banjul", country: "Gambia", city: "Banjul", zone: "Africa/Banjul" },
  { id: "asia-tbilisi", country: "Georgia", city: "Tbilisi", zone: "Asia/Tbilisi" },
  { id: "europe-berlin", country: "Germany", city: "Berlin", zone: "Europe/Berlin" },
  { id: "europe-busingen", country: "Germany", city: "Busingen", zone: "Europe/Busingen" },
  { id: "africa-accra", country: "Ghana", city: "Accra", zone: "Africa/Accra" },
  { id: "europe-gibraltar", country: "Gibraltar", city: "Gibraltar", zone: "Europe/Gibraltar" },
  { id: "europe-athens", country: "Greece", city: "Athens", zone: "Europe/Athens" },
  { id: "america-danmarkshavn", country: "Greenland", city: "Danmarkshavn", zone: "America/Danmarkshavn" },
  { id: "america-godthab", country: "Greenland", city: "Godthab", zone: "America/Godthab" },
  { id: "america-scoresbysund", country: "Greenland", city: "Scoresbysund", zone: "America/Scoresbysund" },
  { id: "america-thule", country: "Greenland", city: "Thule", zone: "America/Thule" },
  { id: "america-grenada", country: "Grenada", city: "Grenada", zone: "America/Grenada" },
  { id: "america-guadeloupe", country: "Guadeloupe", city: "Guadeloupe", zone: "America/Guadeloupe" },
  { id: "pacific-guam", country: "Guam", city: "Guam", zone: "Pacific/Guam" },
  { id: "america-guatemala", country: "Guatemala", city: "Guatemala", zone: "America/Guatemala" },
  { id: "europe-guernsey", country: "Guernsey", city: "Guernsey", zone: "Europe/Guernsey" },
  { id: "africa-conakry", country: "Guinea", city: "Conakry", zone: "Africa/Conakry" },
  { id: "africa-bissau", country: "Guinea-Bissau", city: "Bissau", zone: "Africa/Bissau" },
  { id: "america-guyana", country: "Guyana", city: "Guyana", zone: "America/Guyana" },
  { id: "america-port-au-prince", country: "Haiti", city: "Port-au-Prince", zone: "America/Port-au-Prince" },
  { id: "america-tegucigalpa", country: "Honduras", city: "Tegucigalpa", zone: "America/Tegucigalpa" },
  { id: "asia-hong-kong", country: "Hong Kong", city: "Hong Kong", zone: "Asia/Hong_Kong" },
  { id: "europe-budapest", country: "Hungary", city: "Budapest", zone: "Europe/Budapest" },
  { id: "atlantic-reykjavik", country: "Iceland", city: "Reykjavik", zone: "Atlantic/Reykjavik" },
  { id: "asia-calcutta", country: "India", city: "Calcutta", zone: "Asia/Calcutta" },
  { id: "asia-jakarta", country: "Indonesia", city: "Jakarta", zone: "Asia/Jakarta" },
  { id: "asia-jayapura", country: "Indonesia", city: "Jayapura", zone: "Asia/Jayapura" },
  { id: "asia-makassar", country: "Indonesia", city: "Makassar", zone: "Asia/Makassar" },
  { id: "asia-pontianak", country: "Indonesia", city: "Pontianak", zone: "Asia/Pontianak" },
  { id: "asia-tehran", country: "Iran", city: "Tehran", zone: "Asia/Tehran" },
  { id: "asia-baghdad", country: "Iraq", city: "Baghdad", zone: "Asia/Baghdad" },
  { id: "europe-dublin", country: "Ireland", city: "Dublin", zone: "Europe/Dublin" },
  { id: "europe-isle-of-man", country: "Isle of Man", city: "Isle of Man", zone: "Europe/Isle_of_Man" },
  { id: "asia-jerusalem", country: "Israel", city: "Jerusalem", zone: "Asia/Jerusalem" },
  { id: "europe-rome", country: "Italy", city: "Rome", zone: "Europe/Rome" },
  { id: "america-jamaica", country: "Jamaica", city: "Jamaica", zone: "America/Jamaica" },
  { id: "asia-tokyo", country: "Japan", city: "Tokyo", zone: "Asia/Tokyo" },
  { id: "europe-jersey", country: "Jersey", city: "Jersey", zone: "Europe/Jersey" },
  { id: "asia-amman", country: "Jordan", city: "Amman", zone: "Asia/Amman" },
  { id: "asia-almaty", country: "Kazakhstan", city: "Almaty", zone: "Asia/Almaty" },
  { id: "asia-aqtau", country: "Kazakhstan", city: "Aqtau", zone: "Asia/Aqtau" },
  { id: "asia-aqtobe", country: "Kazakhstan", city: "Aqtobe", zone: "Asia/Aqtobe" },
  { id: "asia-atyrau", country: "Kazakhstan", city: "Atyrau", zone: "Asia/Atyrau" },
  { id: "asia-oral", country: "Kazakhstan", city: "Oral", zone: "Asia/Oral" },
  { id: "asia-qostanay", country: "Kazakhstan", city: "Qostanay", zone: "Asia/Qostanay" },
  { id: "asia-qyzylorda", country: "Kazakhstan", city: "Qyzylorda", zone: "Asia/Qyzylorda" },
  { id: "africa-nairobi", country: "Kenya", city: "Nairobi", zone: "Africa/Nairobi" },
  { id: "pacific-enderbury", country: "Kiribati", city: "Enderbury", zone: "Pacific/Enderbury" },
  { id: "pacific-kiritimati", country: "Kiribati", city: "Kiritimati", zone: "Pacific/Kiritimati" },
  { id: "pacific-tarawa", country: "Kiribati", city: "Tarawa", zone: "Pacific/Tarawa" },
  { id: "asia-kuwait", country: "Kuwait", city: "Kuwait", zone: "Asia/Kuwait" },
  { id: "asia-bishkek", country: "Kyrgyzstan", city: "Bishkek", zone: "Asia/Bishkek" },
  { id: "asia-vientiane", country: "Laos", city: "Vientiane", zone: "Asia/Vientiane" },
  { id: "europe-riga", country: "Latvia", city: "Riga", zone: "Europe/Riga" },
  { id: "asia-beirut", country: "Lebanon", city: "Beirut", zone: "Asia/Beirut" },
  { id: "africa-maseru", country: "Lesotho", city: "Maseru", zone: "Africa/Maseru" },
  { id: "africa-monrovia", country: "Liberia", city: "Monrovia", zone: "Africa/Monrovia" },
  { id: "africa-tripoli", country: "Libya", city: "Tripoli", zone: "Africa/Tripoli" },
  { id: "europe-vaduz", country: "Liechtenstein", city: "Vaduz", zone: "Europe/Vaduz" },
  { id: "europe-vilnius", country: "Lithuania", city: "Vilnius", zone: "Europe/Vilnius" },
  { id: "europe-luxembourg", country: "Luxembourg", city: "Luxembourg", zone: "Europe/Luxembourg" },
  { id: "asia-macau", country: "Macau", city: "Macau", zone: "Asia/Macau" },
  { id: "indian-antananarivo", country: "Madagascar", city: "Antananarivo", zone: "Indian/Antananarivo" },
  { id: "africa-blantyre", country: "Malawi", city: "Blantyre", zone: "Africa/Blantyre" },
  { id: "asia-kuala-lumpur", country: "Malaysia", city: "Kuala Lumpur", zone: "Asia/Kuala_Lumpur" },
  { id: "asia-kuching", country: "Malaysia", city: "Kuching", zone: "Asia/Kuching" },
  { id: "indian-maldives", country: "Maldives", city: "Maldives", zone: "Indian/Maldives" },
  { id: "africa-bamako", country: "Mali", city: "Bamako", zone: "Africa/Bamako" },
  { id: "europe-malta", country: "Malta", city: "Malta", zone: "Europe/Malta" },
  { id: "pacific-kwajalein", country: "Marshall Islands", city: "Kwajalein", zone: "Pacific/Kwajalein" },
  { id: "pacific-majuro", country: "Marshall Islands", city: "Majuro", zone: "Pacific/Majuro" },
  { id: "america-martinique", country: "Martinique", city: "Martinique", zone: "America/Martinique" },
  { id: "africa-nouakchott", country: "Mauritania", city: "Nouakchott", zone: "Africa/Nouakchott" },
  { id: "indian-mauritius", country: "Mauritius", city: "Mauritius", zone: "Indian/Mauritius" },
  { id: "indian-mayotte", country: "Mayotte", city: "Mayotte", zone: "Indian/Mayotte" },
  { id: "america-bahia-banderas", country: "Mexico", city: "Bahia Banderas", zone: "America/Bahia_Banderas" },
  { id: "america-cancun", country: "Mexico", city: "Cancun", zone: "America/Cancun" },
  { id: "america-chihuahua", country: "Mexico", city: "Chihuahua", zone: "America/Chihuahua" },
  { id: "america-ciudad-juarez", country: "Mexico", city: "Ciudad Juarez", zone: "America/Ciudad_Juarez" },
  { id: "america-hermosillo", country: "Mexico", city: "Hermosillo", zone: "America/Hermosillo" },
  { id: "america-matamoros", country: "Mexico", city: "Matamoros", zone: "America/Matamoros" },
  { id: "america-mazatlan", country: "Mexico", city: "Mazatlan", zone: "America/Mazatlan" },
  { id: "america-merida", country: "Mexico", city: "Merida", zone: "America/Merida" },
  { id: "america-mexico-city", country: "Mexico", city: "Mexico City", zone: "America/Mexico_City" },
  { id: "america-monterrey", country: "Mexico", city: "Monterrey", zone: "America/Monterrey" },
  { id: "america-ojinaga", country: "Mexico", city: "Ojinaga", zone: "America/Ojinaga" },
  { id: "america-tijuana", country: "Mexico", city: "Tijuana", zone: "America/Tijuana" },
  { id: "pacific-kosrae", country: "Micronesia", city: "Kosrae", zone: "Pacific/Kosrae" },
  { id: "pacific-ponape", country: "Micronesia", city: "Ponape", zone: "Pacific/Ponape" },
  { id: "pacific-truk", country: "Micronesia", city: "Truk", zone: "Pacific/Truk" },
  { id: "europe-chisinau", country: "Moldova", city: "Chisinau", zone: "Europe/Chisinau" },
  { id: "europe-monaco", country: "Monaco", city: "Monaco", zone: "Europe/Monaco" },
  { id: "asia-hovd", country: "Mongolia", city: "Hovd", zone: "Asia/Hovd" },
  { id: "asia-ulaanbaatar", country: "Mongolia", city: "Ulaanbaatar", zone: "Asia/Ulaanbaatar" },
  { id: "europe-podgorica", country: "Montenegro", city: "Podgorica", zone: "Europe/Podgorica" },
  { id: "america-montserrat", country: "Montserrat", city: "Montserrat", zone: "America/Montserrat" },
  { id: "africa-casablanca", country: "Morocco", city: "Casablanca", zone: "Africa/Casablanca" },
  { id: "africa-maputo", country: "Mozambique", city: "Maputo", zone: "Africa/Maputo" },
  { id: "asia-rangoon", country: "Myanmar", city: "Rangoon", zone: "Asia/Rangoon" },
  { id: "africa-windhoek", country: "Namibia", city: "Windhoek", zone: "Africa/Windhoek" },
  { id: "pacific-nauru", country: "Nauru", city: "Nauru", zone: "Pacific/Nauru" },
  { id: "asia-katmandu", country: "Nepal", city: "Katmandu", zone: "Asia/Katmandu" },
  { id: "europe-amsterdam", country: "Netherlands", city: "Amsterdam", zone: "Europe/Amsterdam" },
  { id: "pacific-noumea", country: "New Caledonia", city: "Noumea", zone: "Pacific/Noumea" },
  { id: "pacific-auckland", country: "New Zealand", city: "Auckland", zone: "Pacific/Auckland" },
  { id: "pacific-chatham", country: "New Zealand", city: "Chatham", zone: "Pacific/Chatham" },
  { id: "america-managua", country: "Nicaragua", city: "Managua", zone: "America/Managua" },
  { id: "africa-niamey", country: "Niger", city: "Niamey", zone: "Africa/Niamey" },
  { id: "africa-lagos", country: "Nigeria", city: "Lagos", zone: "Africa/Lagos" },
  { id: "pacific-niue", country: "Niue", city: "Niue", zone: "Pacific/Niue" },
  { id: "asia-pyongyang", country: "North Korea", city: "Pyongyang", zone: "Asia/Pyongyang" },
  { id: "europe-skopje", country: "North Macedonia", city: "Skopje", zone: "Europe/Skopje" },
  { id: "pacific-saipan", country: "Northern Mariana Islands", city: "Saipan", zone: "Pacific/Saipan" },
  { id: "europe-oslo", country: "Norway", city: "Oslo", zone: "Europe/Oslo" },
  { id: "asia-muscat", country: "Oman", city: "Muscat", zone: "Asia/Muscat" },
  { id: "asia-karachi", country: "Pakistan", city: "Karachi", zone: "Asia/Karachi" },
  { id: "pacific-palau", country: "Palau", city: "Palau", zone: "Pacific/Palau" },
  { id: "asia-gaza", country: "Palestine", city: "Gaza", zone: "Asia/Gaza" },
  { id: "asia-hebron", country: "Palestine", city: "Hebron", zone: "Asia/Hebron" },
  { id: "america-panama", country: "Panama", city: "Panama", zone: "America/Panama" },
  { id: "pacific-bougainville", country: "Papua New Guinea", city: "Bougainville", zone: "Pacific/Bougainville" },
  { id: "pacific-port-moresby", country: "Papua New Guinea", city: "Port Moresby", zone: "Pacific/Port_Moresby" },
  { id: "america-asuncion", country: "Paraguay", city: "Asuncion", zone: "America/Asuncion" },
  { id: "america-lima", country: "Peru", city: "Lima", zone: "America/Lima" },
  { id: "asia-manila", country: "Philippines", city: "Manila", zone: "Asia/Manila" },
  { id: "pacific-pitcairn", country: "Pitcairn Islands", city: "Pitcairn", zone: "Pacific/Pitcairn" },
  { id: "europe-warsaw", country: "Poland", city: "Warsaw", zone: "Europe/Warsaw" },
  { id: "atlantic-azores", country: "Portugal", city: "Azores", zone: "Atlantic/Azores" },
  { id: "europe-lisbon", country: "Portugal", city: "Lisbon", zone: "Europe/Lisbon" },
  { id: "atlantic-madeira", country: "Portugal", city: "Madeira", zone: "Atlantic/Madeira" },
  { id: "america-puerto-rico", country: "Puerto Rico", city: "Puerto Rico", zone: "America/Puerto_Rico" },
  { id: "asia-qatar", country: "Qatar", city: "Qatar", zone: "Asia/Qatar" },
  { id: "indian-reunion", country: "Réunion", city: "Reunion", zone: "Indian/Reunion" },
  { id: "europe-bucharest", country: "Romania", city: "Bucharest", zone: "Europe/Bucharest" },
  { id: "asia-anadyr", country: "Russia", city: "Anadyr", zone: "Asia/Anadyr" },
  { id: "europe-astrakhan", country: "Russia", city: "Astrakhan", zone: "Europe/Astrakhan" },
  { id: "asia-barnaul", country: "Russia", city: "Barnaul", zone: "Asia/Barnaul" },
  { id: "asia-chita", country: "Russia", city: "Chita", zone: "Asia/Chita" },
  { id: "asia-irkutsk", country: "Russia", city: "Irkutsk", zone: "Asia/Irkutsk" },
  { id: "europe-kaliningrad", country: "Russia", city: "Kaliningrad", zone: "Europe/Kaliningrad" },
  { id: "asia-kamchatka", country: "Russia", city: "Kamchatka", zone: "Asia/Kamchatka" },
  { id: "asia-khandyga", country: "Russia", city: "Khandyga", zone: "Asia/Khandyga" },
  { id: "europe-kirov", country: "Russia", city: "Kirov", zone: "Europe/Kirov" },
  { id: "asia-krasnoyarsk", country: "Russia", city: "Krasnoyarsk", zone: "Asia/Krasnoyarsk" },
  { id: "asia-magadan", country: "Russia", city: "Magadan", zone: "Asia/Magadan" },
  { id: "europe-moscow", country: "Russia", city: "Moscow", zone: "Europe/Moscow" },
  { id: "asia-novokuznetsk", country: "Russia", city: "Novokuznetsk", zone: "Asia/Novokuznetsk" },
  { id: "asia-novosibirsk", country: "Russia", city: "Novosibirsk", zone: "Asia/Novosibirsk" },
  { id: "asia-omsk", country: "Russia", city: "Omsk", zone: "Asia/Omsk" },
  { id: "asia-sakhalin", country: "Russia", city: "Sakhalin", zone: "Asia/Sakhalin" },
  { id: "europe-samara", country: "Russia", city: "Samara", zone: "Europe/Samara" },
  { id: "europe-saratov", country: "Russia", city: "Saratov", zone: "Europe/Saratov" },
  { id: "asia-srednekolymsk", country: "Russia", city: "Srednekolymsk", zone: "Asia/Srednekolymsk" },
  { id: "asia-tomsk", country: "Russia", city: "Tomsk", zone: "Asia/Tomsk" },
  { id: "europe-ulyanovsk", country: "Russia", city: "Ulyanovsk", zone: "Europe/Ulyanovsk" },
  { id: "asia-ust-nera", country: "Russia", city: "Ust-Nera", zone: "Asia/Ust-Nera" },
  { id: "asia-vladivostok", country: "Russia", city: "Vladivostok", zone: "Asia/Vladivostok" },
  { id: "europe-volgograd", country: "Russia", city: "Volgograd", zone: "Europe/Volgograd" },
  { id: "asia-yakutsk", country: "Russia", city: "Yakutsk", zone: "Asia/Yakutsk" },
  { id: "asia-yekaterinburg", country: "Russia", city: "Yekaterinburg", zone: "Asia/Yekaterinburg" },
  { id: "africa-kigali", country: "Rwanda", city: "Kigali", zone: "Africa/Kigali" },
  { id: "america-st-barthelemy", country: "Saint Barthélemy", city: "St Barthelemy", zone: "America/St_Barthelemy" },
  { id: "atlantic-st-helena", country: "Saint Helena", city: "St Helena", zone: "Atlantic/St_Helena" },
  { id: "america-st-kitts", country: "Saint Kitts and Nevis", city: "St Kitts", zone: "America/St_Kitts" },
  { id: "america-st-lucia", country: "Saint Lucia", city: "St Lucia", zone: "America/St_Lucia" },
  { id: "america-marigot", country: "Saint Martin", city: "Marigot", zone: "America/Marigot" },
  { id: "america-miquelon", country: "Saint Pierre and Miquelon", city: "Miquelon", zone: "America/Miquelon" },
  { id: "america-st-vincent", country: "Saint Vincent and the Grenadines", city: "St Vincent", zone: "America/St_Vincent" },
  { id: "pacific-apia", country: "Samoa", city: "Apia", zone: "Pacific/Apia" },
  { id: "europe-san-marino", country: "San Marino", city: "San Marino", zone: "Europe/San_Marino" },
  { id: "africa-sao-tome", country: "São Tomé and Príncipe", city: "Sao Tome", zone: "Africa/Sao_Tome" },
  { id: "asia-riyadh", country: "Saudi Arabia", city: "Riyadh", zone: "Asia/Riyadh" },
  { id: "africa-dakar", country: "Senegal", city: "Dakar", zone: "Africa/Dakar" },
  { id: "europe-belgrade", country: "Serbia", city: "Belgrade", zone: "Europe/Belgrade" },
  { id: "indian-mahe", country: "Seychelles", city: "Mahe", zone: "Indian/Mahe" },
  { id: "africa-freetown", country: "Sierra Leone", city: "Freetown", zone: "Africa/Freetown" },
  { id: "asia-singapore", country: "Singapore", city: "Singapore", zone: "Asia/Singapore" },
  { id: "america-lower-princes", country: "Sint Maarten", city: "Lower Princes", zone: "America/Lower_Princes" },
  { id: "europe-bratislava", country: "Slovakia", city: "Bratislava", zone: "Europe/Bratislava" },
  { id: "europe-ljubljana", country: "Slovenia", city: "Ljubljana", zone: "Europe/Ljubljana" },
  { id: "pacific-guadalcanal", country: "Solomon Islands", city: "Guadalcanal", zone: "Pacific/Guadalcanal" },
  { id: "africa-mogadishu", country: "Somalia", city: "Mogadishu", zone: "Africa/Mogadishu" },
  { id: "africa-johannesburg", country: "South Africa", city: "Johannesburg", zone: "Africa/Johannesburg" },
  { id: "atlantic-south-georgia", country: "South Georgia and South Sandwich Islands", city: "South Georgia", zone: "Atlantic/South_Georgia" },
  { id: "asia-seoul", country: "South Korea", city: "Seoul", zone: "Asia/Seoul" },
  { id: "africa-juba", country: "South Sudan", city: "Juba", zone: "Africa/Juba" },
  { id: "atlantic-canary", country: "Spain", city: "Canary", zone: "Atlantic/Canary" },
  { id: "africa-ceuta", country: "Spain", city: "Ceuta", zone: "Africa/Ceuta" },
  { id: "europe-madrid", country: "Spain", city: "Madrid", zone: "Europe/Madrid" },
  { id: "asia-colombo", country: "Sri Lanka", city: "Colombo", zone: "Asia/Colombo" },
  { id: "africa-khartoum", country: "Sudan", city: "Khartoum", zone: "Africa/Khartoum" },
  { id: "america-paramaribo", country: "Suriname", city: "Paramaribo", zone: "America/Paramaribo" },
  { id: "arctic-longyearbyen", country: "Svalbard and Jan Mayen", city: "Longyearbyen", zone: "Arctic/Longyearbyen" },
  { id: "europe-stockholm", country: "Sweden", city: "Stockholm", zone: "Europe/Stockholm" },
  { id: "europe-zurich", country: "Switzerland", city: "Zurich", zone: "Europe/Zurich" },
  { id: "asia-damascus", country: "Syria", city: "Damascus", zone: "Asia/Damascus" },
  { id: "asia-taipei", country: "Taiwan", city: "Taipei", zone: "Asia/Taipei" },
  { id: "asia-dushanbe", country: "Tajikistan", city: "Dushanbe", zone: "Asia/Dushanbe" },
  { id: "africa-dar-es-salaam", country: "Tanzania", city: "Dar es Salaam", zone: "Africa/Dar_es_Salaam" },
  { id: "asia-bangkok", country: "Thailand", city: "Bangkok", zone: "Asia/Bangkok" },
  { id: "africa-lome", country: "Togo", city: "Lome", zone: "Africa/Lome" },
  { id: "pacific-fakaofo", country: "Tokelau", city: "Fakaofo", zone: "Pacific/Fakaofo" },
  { id: "pacific-tongatapu", country: "Tonga", city: "Tongatapu", zone: "Pacific/Tongatapu" },
  { id: "america-port-of-spain", country: "Trinidad and Tobago", city: "Port of Spain", zone: "America/Port_of_Spain" },
  { id: "africa-tunis", country: "Tunisia", city: "Tunis", zone: "Africa/Tunis" },
  { id: "europe-istanbul", country: "Turkey", city: "Istanbul", zone: "Europe/Istanbul" },
  { id: "asia-ashgabat", country: "Turkmenistan", city: "Ashgabat", zone: "Asia/Ashgabat" },
  { id: "america-grand-turk", country: "Turks and Caicos Islands", city: "Grand Turk", zone: "America/Grand_Turk" },
  { id: "pacific-funafuti", country: "Tuvalu", city: "Funafuti", zone: "Pacific/Funafuti" },
  { id: "america-st-thomas", country: "U.S. Virgin Islands", city: "St Thomas", zone: "America/St_Thomas" },
  { id: "africa-kampala", country: "Uganda", city: "Kampala", zone: "Africa/Kampala" },
  { id: "europe-kiev", country: "Ukraine", city: "Kiev", zone: "Europe/Kiev" },
  { id: "europe-simferopol", country: "Ukraine", city: "Simferopol", zone: "Europe/Simferopol" },
  { id: "asia-dubai", country: "United Arab Emirates", city: "Dubai", zone: "Asia/Dubai" },
  { id: "europe-london", country: "United Kingdom", city: "London", zone: "Europe/London" },
  { id: "america-adak", country: "United States", city: "Adak", zone: "America/Adak" },
  { id: "america-anchorage", country: "United States", city: "Anchorage", zone: "America/Anchorage" },
  { id: "america-boise", country: "United States", city: "Boise", zone: "America/Boise" },
  { id: "america-chicago", country: "United States", city: "Chicago", zone: "America/Chicago" },
  { id: "america-denver", country: "United States", city: "Denver", zone: "America/Denver" },
  { id: "america-detroit", country: "United States", city: "Detroit", zone: "America/Detroit" },
  { id: "pacific-honolulu", country: "United States", city: "Honolulu", zone: "Pacific/Honolulu" },
  { id: "america-indiana-knox", country: "United States", city: "Indiana – Knox", zone: "America/Indiana/Knox" },
  { id: "america-indiana-marengo", country: "United States", city: "Indiana – Marengo", zone: "America/Indiana/Marengo" },
  { id: "america-indiana-petersburg", country: "United States", city: "Indiana – Petersburg", zone: "America/Indiana/Petersburg" },
  { id: "america-indiana-tell-city", country: "United States", city: "Indiana – Tell City", zone: "America/Indiana/Tell_City" },
  { id: "america-indiana-vevay", country: "United States", city: "Indiana – Vevay", zone: "America/Indiana/Vevay" },
  { id: "america-indiana-vincennes", country: "United States", city: "Indiana – Vincennes", zone: "America/Indiana/Vincennes" },
  { id: "america-indiana-winamac", country: "United States", city: "Indiana – Winamac", zone: "America/Indiana/Winamac" },
  { id: "america-indianapolis", country: "United States", city: "Indianapolis", zone: "America/Indianapolis" },
  { id: "america-juneau", country: "United States", city: "Juneau", zone: "America/Juneau" },
  { id: "america-kentucky-monticello", country: "United States", city: "Kentucky – Monticello", zone: "America/Kentucky/Monticello" },
  { id: "america-los-angeles", country: "United States", city: "Los Angeles", zone: "America/Los_Angeles" },
  { id: "america-louisville", country: "United States", city: "Louisville", zone: "America/Louisville" },
  { id: "america-menominee", country: "United States", city: "Menominee", zone: "America/Menominee" },
  { id: "america-metlakatla", country: "United States", city: "Metlakatla", zone: "America/Metlakatla" },
  { id: "pacific-midway", country: "United States", city: "Midway", zone: "Pacific/Midway" },
  { id: "america-new-york", country: "United States", city: "New York", zone: "America/New_York" },
  { id: "america-nome", country: "United States", city: "Nome", zone: "America/Nome" },
  { id: "america-north-dakota-beulah", country: "United States", city: "North Dakota – Beulah", zone: "America/North_Dakota/Beulah" },
  { id: "america-north-dakota-center", country: "United States", city: "North Dakota – Center", zone: "America/North_Dakota/Center" },
  { id: "america-north-dakota-new-salem", country: "United States", city: "North Dakota – New Salem", zone: "America/North_Dakota/New_Salem" },
  { id: "america-phoenix", country: "United States", city: "Phoenix", zone: "America/Phoenix" },
  { id: "america-sitka", country: "United States", city: "Sitka", zone: "America/Sitka" },
  { id: "pacific-wake", country: "United States", city: "Wake", zone: "Pacific/Wake" },
  { id: "america-yakutat", country: "United States", city: "Yakutat", zone: "America/Yakutat" },
  { id: "america-montevideo", country: "Uruguay", city: "Montevideo", zone: "America/Montevideo" },
  { id: "utc", country: "UTC", city: "Coordinated Universal Time", zone: "UTC" },
  { id: "asia-samarkand", country: "Uzbekistan", city: "Samarkand", zone: "Asia/Samarkand" },
  { id: "asia-tashkent", country: "Uzbekistan", city: "Tashkent", zone: "Asia/Tashkent" },
  { id: "pacific-efate", country: "Vanuatu", city: "Efate", zone: "Pacific/Efate" },
  { id: "europe-vatican", country: "Vatican City", city: "Vatican", zone: "Europe/Vatican" },
  { id: "america-caracas", country: "Venezuela", city: "Caracas", zone: "America/Caracas" },
  { id: "asia-saigon", country: "Vietnam", city: "Saigon", zone: "Asia/Saigon" },
  { id: "pacific-wallis", country: "Wallis and Futuna", city: "Wallis", zone: "Pacific/Wallis" },
  { id: "africa-el-aaiun", country: "Western Sahara", city: "El Aaiun", zone: "Africa/El_Aaiun" },
  { id: "asia-aden", country: "Yemen", city: "Aden", zone: "Asia/Aden" },
  { id: "africa-lusaka", country: "Zambia", city: "Lusaka", zone: "Africa/Lusaka" },
  { id: "africa-harare", country: "Zimbabwe", city: "Harare", zone: "Africa/Harare" },
];
