export interface TimezoneOption {
  id: string;
  country: string;
  city: string;
  zone: string;
}

export const TIMEZONE_OPTIONS: TimezoneOption[] = [
  { id: "utc", country: "UTC", city: "Coordinated Universal Time", zone: "UTC" },
  { id: "us-ny", country: "United States", city: "New York", zone: "America/New_York" },
  { id: "us-chi", country: "United States", city: "Chicago", zone: "America/Chicago" },
  { id: "us-den", country: "United States", city: "Denver", zone: "America/Denver" },
  { id: "us-la", country: "United States", city: "Los Angeles", zone: "America/Los_Angeles" },
  { id: "us-anc", country: "United States", city: "Anchorage", zone: "America/Anchorage" },
  { id: "us-hon", country: "United States", city: "Honolulu", zone: "Pacific/Honolulu" },
  { id: "ca-tor", country: "Canada", city: "Toronto", zone: "America/Toronto" },
  { id: "ca-van", country: "Canada", city: "Vancouver", zone: "America/Vancouver" },
  { id: "mx-mex", country: "Mexico", city: "Mexico City", zone: "America/Mexico_City" },
  { id: "br-sao", country: "Brazil", city: "Sao Paulo", zone: "America/Sao_Paulo" },
  { id: "ar-bue", country: "Argentina", city: "Buenos Aires", zone: "America/Argentina/Buenos_Aires" },
  { id: "gb-lon", country: "United Kingdom", city: "London", zone: "Europe/London" },
  { id: "ie-dub", country: "Ireland", city: "Dublin", zone: "Europe/Dublin" },
  { id: "pt-lis", country: "Portugal", city: "Lisbon", zone: "Europe/Lisbon" },
  { id: "fr-par", country: "France", city: "Paris", zone: "Europe/Paris" },
  { id: "de-ber", country: "Germany", city: "Berlin", zone: "Europe/Berlin" },
  { id: "es-mad", country: "Spain", city: "Madrid", zone: "Europe/Madrid" },
  { id: "it-rom", country: "Italy", city: "Rome", zone: "Europe/Rome" },
  { id: "nl-ams", country: "Netherlands", city: "Amsterdam", zone: "Europe/Amsterdam" },
  { id: "ch-zur", country: "Switzerland", city: "Zurich", zone: "Europe/Zurich" },
  { id: "se-sto", country: "Sweden", city: "Stockholm", zone: "Europe/Stockholm" },
  { id: "no-osl", country: "Norway", city: "Oslo", zone: "Europe/Oslo" },
  { id: "dk-cop", country: "Denmark", city: "Copenhagen", zone: "Europe/Copenhagen" },
  { id: "fi-hel", country: "Finland", city: "Helsinki", zone: "Europe/Helsinki" },
  { id: "pl-war", country: "Poland", city: "Warsaw", zone: "Europe/Warsaw" },
  { id: "gr-ath", country: "Greece", city: "Athens", zone: "Europe/Athens" },
  { id: "tr-ist", country: "Turkey", city: "Istanbul", zone: "Europe/Istanbul" },
  { id: "ru-mos", country: "Russia", city: "Moscow", zone: "Europe/Moscow" },
  { id: "ua-kie", country: "Ukraine", city: "Kyiv", zone: "Europe/Kyiv" },
  { id: "za-jhb", country: "South Africa", city: "Johannesburg", zone: "Africa/Johannesburg" },
  { id: "eg-cai", country: "Egypt", city: "Cairo", zone: "Africa/Cairo" },
  { id: "ng-lag", country: "Nigeria", city: "Lagos", zone: "Africa/Lagos" },
  { id: "ke-nai", country: "Kenya", city: "Nairobi", zone: "Africa/Nairobi" },
  { id: "ae-dxb", country: "United Arab Emirates", city: "Dubai", zone: "Asia/Dubai" },
  { id: "sa-riy", country: "Saudi Arabia", city: "Riyadh", zone: "Asia/Riyadh" },
  { id: "il-tlv", country: "Israel", city: "Tel Aviv", zone: "Asia/Jerusalem" },
  { id: "in-kol", country: "India", city: "Mumbai / New Delhi", zone: "Asia/Kolkata" },
  { id: "pk-kar", country: "Pakistan", city: "Karachi", zone: "Asia/Karachi" },
  { id: "bd-dha", country: "Bangladesh", city: "Dhaka", zone: "Asia/Dhaka" },
  { id: "np-ktm", country: "Nepal", city: "Kathmandu", zone: "Asia/Kathmandu" },
  { id: "th-bkk", country: "Thailand", city: "Bangkok", zone: "Asia/Bangkok" },
  { id: "vn-han", country: "Vietnam", city: "Hanoi", zone: "Asia/Ho_Chi_Minh" },
  { id: "id-jkt", country: "Indonesia", city: "Jakarta", zone: "Asia/Jakarta" },
  { id: "sg-sin", country: "Singapore", city: "Singapore", zone: "Asia/Singapore" },
  { id: "my-kul", country: "Malaysia", city: "Kuala Lumpur", zone: "Asia/Kuala_Lumpur" },
  { id: "ph-man", country: "Philippines", city: "Manila", zone: "Asia/Manila" },
  { id: "cn-sha", country: "China", city: "Shanghai / Beijing", zone: "Asia/Shanghai" },
  { id: "hk-hkg", country: "Hong Kong", city: "Hong Kong", zone: "Asia/Hong_Kong" },
  { id: "tw-tpe", country: "Taiwan", city: "Taipei", zone: "Asia/Taipei" },
  { id: "kr-sel", country: "South Korea", city: "Seoul", zone: "Asia/Seoul" },
  { id: "jp-tok", country: "Japan", city: "Tokyo", zone: "Asia/Tokyo" },
  { id: "au-syd", country: "Australia", city: "Sydney", zone: "Australia/Sydney" },
  { id: "au-per", country: "Australia", city: "Perth", zone: "Australia/Perth" },
  { id: "au-adl", country: "Australia", city: "Adelaide", zone: "Australia/Adelaide" },
  { id: "nz-auk", country: "New Zealand", city: "Auckland", zone: "Pacific/Auckland" },
];
